version: '2'
services:
  sensordata_db:
    image: postgres
  api:
    build: .
    command: sensor-api
    ports:
      - "5000:5000"
    depends_on:
      - sensordata_db
  subscriber:
    build: .
    command: sensor-subscribe
    depends_on:
      - sensordata_db
