apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sensordb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: sensordb
    spec:
      containers:
      - name: sensordb
        image: postgres
        ports:
        - containerPort: 5432
